#ifndef KTRACE_H
#define KTRACE_H
#include <sys/types.h>

#define KTRACE_EVENT_LOW 0

/* All the kernel calls. */
#define KTRACE_SYS_FORK (KTRACE_EVENT_LOW+0)
#define KTRACE_SYS_EXEC (KTRACE_EVENT_LOW+1)
#define KTRACE_SYS_CLEAR (KTRACE_EVENT_LOW+2)
#define KTRACE_SYS_SCHEDULE (KTRACE_EVENT_LOW+3)
#define KTRACE_SYS_PRIVCTL (KTRACE_EVENT_LOW+4)
#define KTRACE_SYS_TRACE (KTRACE_EVENT_LOW+5)
#define KTRACE_SYS_KILL (KTRACE_EVENT_LOW+6)
#define KTRACE_SYS_GETKSIG (KTRACE_EVENT_LOW+7)
#define KTRACE_SYS_ENDKSIG (KTRACE_EVENT_LOW+8)
#define KTRACE_SYS_SIGSEND (KTRACE_EVENT_LOW+9)
#define KTRACE_SYS_SIGRETURN (KTRACE_EVENT_LOW+10)
#define KTRACE_SYS_MEMSET (KTRACE_EVENT_LOW+11)
#define KTRACE_SYS_UMAP (KTRACE_EVENT_LOW+12)
#define KTRACE_SYS_VIRCOPY (KTRACE_EVENT_LOW+13)
#define KTRACE_SYS_PHYSCOPY (KTRACE_EVENT_LOW+14)
#define KTRACE_SYS_UMAP_REMOTE (KTRACE_EVENT_LOW+15)
#define KTRACE_SYS_VUMAP (KTRACE_EVENT_LOW+16)
#define KTRACE_SYS_IRQCTL (KTRACE_EVENT_LOW+17)
#define KTRACE_SYS_DEVIO (KTRACE_EVENT_LOW+18)
#define KTRACE_SYS_SDEVIO (KTRACE_EVENT_LOW+19)
#define KTRACE_SYS_VDEVIO (KTRACE_EVENT_LOW+20)
#define KTRACE_SYS_SETALARM (KTRACE_EVENT_LOW+21)
#define KTRACE_SYS_TIMES (KTRACE_EVENT_LOW+22)
#define KTRACE_SYS_GETINFO (KTRACE_EVENT_LOW+23)
#define KTRACE_SYS_ABORT (KTRACE_EVENT_LOW+24)
#define KTRACE_SYS_IOPENABLE (KTRACE_EVENT_LOW+25)
#define KTRACE_SYS_SAFECOPYFROM (KTRACE_EVENT_LOW+26)
#define KTRACE_SYS_SAFECOPYTO (KTRACE_EVENT_LOW+27)
#define KTRACE_SYS_VSAFECOPY (KTRACE_EVENT_LOW+28)
#define KTRACE_SYS_SETGRANT (KTRACE_EVENT_LOW+29)
#define KTRACE_SYS_READBIOS (KTRACE_EVENT_LOW+30)
#define KTRACE_SYS_SPROF (KTRACE_EVENT_LOW+31)
#define KTRACE_SYS_STIME (KTRACE_EVENT_LOW+32)
#define KTRACE_SYS_SETTIME (KTRACE_EVENT_LOW+33)
#define KTRACE_SYS_VMCTL (KTRACE_EVENT_LOW+34)
#define KTRACE_SYS_DIAGCTL (KTRACE_EVENT_LOW+35)
#define KTRACE_SYS_VTIMER (KTRACE_EVENT_LOW+36)
#define KTRACE_SYS_RUNCTL (KTRACE_EVENT_LOW+37)
#define KTRACE_SYS_GETMCONTEXT (KTRACE_EVENT_LOW+38)
#define KTRACE_SYS_SETMCONTEXT (KTRACE_EVENT_LOW+39)
#define KTRACE_SYS_UPDATE (KTRACE_EVENT_LOW+40)
#define KTRACE_SYS_EXIT (KTRACE_EVENT_LOW+41)
#define KTRACE_SYS_SCHEDCTL (KTRACE_EVENT_LOW+42)
#define KTRACE_SYS_STATECTL (KTRACE_EVENT_LOW+43)
#define KTRACE_SYS_SAFEMEMSET (KTRACE_EVENT_LOW+44)
#define KTRACE_SYS_PADCONF (KTRACE_EVENT_LOW+45)

/* All the IPC calls. */
#define KTRACE_SEND (KTRACE_EVENT_LOW+46)
#define KTRACE_RECEIVE (KTRACE_EVENT_LOW+47)
#define KTRACE_SENDREC (KTRACE_EVENT_LOW+48)
#define KTRACE_NOTIFY (KTRACE_EVENT_LOW+49)
#define KTRACE_SENDNB (KTRACE_EVENT_LOW+50)
#define KTRACE_MINIX_KERNINFO (KTRACE_EVENT_LOW+51)
#define KTRACE_SENDA (KTRACE_EVENT_LOW+52)

/* BKL operations. */
#define KTRACE_BKL_TRY (KTRACE_EVENT_LOW+53)
#define KTRACE_BKL_ACQUIRE (KTRACE_EVENT_LOW+54)
#define KTRACE_BKL_RELEASE (KTRACE_EVENT_LOW+55)

/* IDLE operations. */
#define KTRACE_IDLE_START (KTRACE_EVENT_LOW+56)
#define KTRACE_IDLE_STOP (KTRACE_EVENT_LOW+57)

/* USER swtich operations. */
#define KTRACE_USER_START (KTRACE_EVENT_LOW+58)
#define KTRACE_USER_STOP (KTRACE_EVENT_LOW+59)

#define KTRACE_EVENT_HIGH KTRACE_BKL_RELEASE
#define KTRACE_NUM_KERNEL_CALLS ((KTRACE_SYS_PADCONF-KTRACE_SYS_EXEC)+1)
#define KTRACE_NUM_IPCS ((KTRACE_SENDA-KTRACE_SEND)+1)

#define KTRACE_IS_KERNEL_CALL(event) \
	(KTRACE_SYS_FORK<=(event)&&(event)<=KTRACE_SYS_PADCONF)

#define KTRACE_IS_IPC(event) \
	(KTRACE_SEND<=(event)&&(event)<=KTRACE_SENDA)

struct kernel_trace_entry {
	u64_t timestamp;
	unsigned char cpu;
	unsigned char event;
};

extern const char *ktzprofile_kc_to_str[47];
extern const char *ktzprofile_ipc_to_str[7];
#endif
